# Generated by Django 3.1.5 on 2021-02-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=5)),
                ('date', models.DateField()),
                ('time_in', models.DateField()),
                ('time_out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=5)),
                ('details', models.TextField()),
                ('ratings', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Membership_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=5)),
                ('plan_id', models.IntegerField(max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.IntegerField(max_length=5)),
                ('details', models.TextField()),
                ('membership_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(max_length=5)),
                ('product_id', models.IntegerField(max_length=5)),
                ('qty', models.IntegerField(max_length=2)),
                ('price', models.IntegerField(max_length=5)),
                ('tot_amt', models.IntegerField(max_length=5)),
                ('delivery_date', models.DateField()),
                ('delivery_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=5)),
                ('ord_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.IntegerField(max_length=5)),
                ('amount', models.IntegerField(max_length=5)),
                ('method', models.CharField(max_length=15)),
                ('transaction_no', models.CharField(max_length=40)),
                ('payment_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('price', models.IntegerField(max_length=5)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('qty', models.IntegerField(max_length=2)),
                ('details', models.TextField()),
                ('price', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=5)),
                ('salary', models.IntegerField(max_length=5)),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(max_length=5)),
                ('mname', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=150)),
                ('mobile', models.IntegerField(max_length=10)),
                ('photo', models.CharField(max_length=100)),
                ('id_proof', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=5)),
                ('diet_chart', models.CharField(max_length=100)),
                ('workout_schedule', models.CharField(max_length=100)),
                ('videos', models.CharField(max_length=100)),
                ('rewards', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
