# Generated by Django 3.1.5 on 2021-02-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_auto_20210224_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feedback_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='membership_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='plan_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product_master',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trainer_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='workout_master',
            name='id',
        ),
        migrations.AddField(
            model_name='attendance_master',
            name='attendance_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='feedback_master',
            name='feedback_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='membership_master',
            name='membership_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_details_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order_master',
            name='order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='payment_master',
            name='payment_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='plan_master',
            name='plan_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product_master',
            name='product_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trainer_details',
            name='trainer_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workout_master',
            name='workout_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendance_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
        migrations.AlterField(
            model_name='feedback_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
        migrations.AlterField(
            model_name='membership_master',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.plan_master'),
        ),
        migrations.AlterField(
            model_name='membership_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.order_master'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.product_master'),
        ),
        migrations.AlterField(
            model_name='order_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
        migrations.AlterField(
            model_name='payment_master',
            name='membership_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.membership_master'),
        ),
        migrations.AlterField(
            model_name='trainer_details',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='type_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
    ]
