# Generated by Django 3.1.5 on 2021-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_auto_20210224_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_master',
            name='ratings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='membership_master',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='tot_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment_master',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan_master',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer_details',
            name='salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='address',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workout_master',
            name='rewards',
            field=models.IntegerField(),
        ),
    ]
