# Generated by Django 3.1.5 on 2021-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_auto_20210224_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='password',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
