# Generated by Django 3.1.5 on 2021-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_auto_20210224_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
