# Generated by Django 3.1.5 on 2021-02-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_auto_20210224_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_master',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='feedback_master',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='membership_master',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order_master',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='trainer_details',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workout_master',
            name='user_id',
        ),
    ]
