# Generated by Django 3.1.5 on 2021-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_auto_20210225_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_master',
            name='id',
        ),
        migrations.AddField(
            model_name='user_master',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
