# Generated by Django 3.1.5 on 2021-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0016_auto_20210225_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='id_proof',
            field=models.FileField(upload_to=''),
        ),
    ]
