# Generated by Django 3.1.5 on 2021-02-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0017_auto_20210225_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
