# Generated by Django 3.1.5 on 2021-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0018_auto_20210225_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_master',
            name='diet_chart',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='workout_master',
            name='videos',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='workout_master',
            name='workout_schedule',
            field=models.FileField(upload_to=''),
        ),
    ]
