# Generated by Django 3.1.5 on 2021-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0019_auto_20210225_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
