# Generated by Django 3.1.5 on 2021-02-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0020_auto_20210226_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_master',
            name='method',
            field=models.CharField(choices=[('Google Pay', 'Gpay'), ('Paytm', 'Paytm'), ('Cash', 'Cash')], max_length=15),
        ),
    ]
