# Generated by Django 3.1.5 on 2021-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0021_auto_20210226_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='id_proof',
            field=models.FilePathField(),
        ),
    ]
