# Generated by Django 3.1.5 on 2021-02-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0024_user_master_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='id_proof',
            field=models.FileField(upload_to=''),
        ),
    ]
