# Generated by Django 3.1.5 on 2021-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0026_auto_20210226_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='mname',
            field=models.CharField(help_text='Member Name', max_length=25),
        ),
    ]
