# Generated by Django 3.1.5 on 2021-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0027_auto_20210226_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='mname',
            field=models.CharField(max_length=25),
        ),
    ]
