# Generated by Django 3.1.5 on 2021-02-26 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0028_auto_20210226_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='photo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
