# Generated by Django 3.1.5 on 2021-03-04 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0041_auto_20210303_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='user_id',
            field=models.IntegerField(auto_created=True, help_text='Id Must Be Between 10000 to 99999', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
