# Generated by Django 3.1.5 on 2021-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0044_auto_20210304_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_master',
            name='attendance_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback_master',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership_master',
            name='membership_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_details_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_master',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_master',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan_master',
            name='plan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product_master',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainer_details',
            name='trainer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_type',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout_master',
            name='workout_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
