# Generated by Django 3.1.5 on 2021-03-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0045_auto_20210308_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_master',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
    ]
