# Generated by Django 3.1.5 on 2021-03-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0046_auto_20210308_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_master',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_master'),
        ),
    ]
