# Generated by Django 5.0.3 on 2024-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0047_auto_20210308_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_master',
            name='membership_status',
            field=models.CharField(help_text='Membership Status', max_length=50),
        ),
    ]
