# Generated by Django 5.0.3 on 2024-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0049_alter_membership_master_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership_master',
            name='membership_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], help_text='Membership Status', max_length=20),
        ),
    ]
