# Generated by Django 5.0.3 on 2024-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0050_alter_membership_master_membership_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_details',
        ),
        migrations.DeleteModel(
            name='Product_master',
        ),
    ]
