# Generated by Django 4.2 on 2024-03-26 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0052_remove_user_master_id_proof_remove_user_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='id_proof',
            field=models.FileField(help_text='Any Government Approved Id(Aadhar/Driving License/PAN Card/Voter Id) <br> Must be .pdf File Only <br> Maximum Size 2MB', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='user_master',
            name='photo',
            field=models.FileField(help_text='Image File of User <br> Must of be .jpg or .png <br> Maximum Size 1MB', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
