# Generated by Django 5.0.3 on 2024-04-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0053_user_master_id_proof_user_master_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Must Contain @ and .', max_length=30, unique=True)),
                ('password', models.CharField(help_text='Password Must be of 6 to 16 Characters ', max_length=16, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Order_master',
        ),
    ]
